apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alpha
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alpha-endpoint
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: alpha_queue_depth
      target:
        type: AverageValue
        averageValue: 100