apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: beta
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: beta-endpoint
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: beta_queue_depth
      target:
        type: AverageValue
        averageValue: 100