apiVersion: v1
kind: Service
metadata:
  name: servicecontrol-audit-service
  labels:
    app: particular-servicecontrol-audit
spec:
  clusterIP: None
  ports:
  - name: api
    port: 44444
    protocol: TCP
    targetPort: 44444
  - name: ravendb-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: ravendb-snmp
    port: 161
    protocol: TCP
    targetPort: 161
  selector:
    app: particular-servicecontrol-audit
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audit-db-files
  labels:
    type: local
spec:
  storageClassName: audit-db-local
  persistentVolumeReclaimPolicy: Retain
  accessModes: [ "ReadWriteOnce"]
  capacity:
    storage: 10Gi
  hostPath:
    type: DirectoryOrCreate
    path: "/tmp/audit-db-files"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: servicecontrol-audit-statefulset
spec:
  serviceName: servicecontrol-audit-service
  replicas: 1
  selector:
    matchLabels:
      app: particular-servicecontrol-audit
  updateStrategy:
    type: OnDelete
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
  volumeClaimTemplates:
  - metadata:
      name: audit-db-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: audit-db-config
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        app: particular-servicecontrol-audit
    spec:
      containers:
        - name: servicecontrol-audit
          image: particular/servicecontrol-audit:latest
          imagePullPolicy: Always
          ports:
          - name: api
            containerPort: 44444
            protocol: TCP
          env:
            - name: TRANSPORTTYPE
              value: "RabbitMQ.QuorumConventionalRouting"
            - name: CONNECTIONSTRING
              value: "host=rabbitmq;username=guest;password=guest"
            - name: RAVENDB_CONNECTIONSTRING
              value: http://localhost:8080
      initContainers:
        - name: servicecontrol-audit-db
          image: particular/servicecontrol-ravendb:latest
          imagePullPolicy: Always
          restartPolicy: Always
          ports:
          - name: ravendb-http
            containerPort: 8080
            protocol: TCP
          - name: ravendb-snmp
            containerPort: 161
            protocol: TCP
          volumeMounts:
          - name: audit-db-data
            mountPath: /var/lib/ravendb/data
          - name: audit-db-config
            mountPath: /var/lib/ravendb/config
        - name: wait-for-ravendb
          image: curlimages/curl:latest
          command: ['curl', '-o', 'ping.json', 'http://localhost:8080/admin/debug/node/ping']
        - name: init-servicecontrol-audit
          image: particular/servicecontrol-audit:latest
          args: ['--setup']
          env:
            - name: TRANSPORTTYPE
              value: "RabbitMQ.QuorumConventionalRouting"
            - name: CONNECTIONSTRING
              value: "host=rabbitmq;username=guest;password=guest"
            - name: RAVENDB_CONNECTIONSTRING
              value: http://localhost:8080
